services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000/api
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"

  backend:
    depends_on:
      - db
    build:
      context: ./backend
    environment:
      # Note that env vars here just for convenience, this is a NOT a prod setup
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:secret1234@db:5432/taskmanagement
      - POSTGRES_DB=taskmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret1234
      - JWT_SECRET=SuperSecretString4321!
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost
        # True during initial prod deployment to sync DB
        # Set false after DB -> synchronized
      -  DB_SYNC=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"

  db:
    image: postgres:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Same thing here
      - POSTGRES_DB=taskmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret1234
    ports:
      - "5432:5432"
