name: Task Management CD

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: Backend
            url: RENDER_DEPLOY_HOOK_BACKEND
            image: "&imgURL=docker.io%2Fbootmanager%2Ftask-manage-backend%3Amain"

          - name: Frontend
            url: RENDER_DEPLOY_HOOK_FRONTEND
            image: "&imgURL=docker.io%2Fbootmanager%2Ftask-manage-frontend%3Amain"

    # Only trigger redeploy on a new image push
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy ${{ matrix.service.name }}
        env:
          deploy_url: ${{ secrets[matrix.service.url] }}${{ matrix.service.image }}
        run: |
          if [ -z "$deploy_url" ]; then
            echo "DEPLOY HOOK NOT SET!"
            exit 1
          fi

          curl "$deploy_url"
