name: Task management CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm run install --workspace ${{ matrix.component }}

      # AUDIT
      - name: Audit node modules
        run: npm audit --audit-level=critical

      # LINT
      - name: Check code
        run: npm run lint --workspace ${{ matrix.component }}

      # RUN TESTS
      - name: Run tests
        run: npm test --workspace ${{ matrix.component }}
