name: Task Management CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set Up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --workspaces

      # AUDIT
      - name: Audit Node Modules
        run: npm audit --audit-level=critical

      # LINT
      - name: Check Code
        run: npm run lint --workspace ${{ matrix.component }}

      # RUN TESTS
      - name: Run Tests
        run: npm test --workspace ${{ matrix.component }}
