name: Task management CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ../..
        run: npm run install:all

      # AUDIT
      - name: Audit node modules
        working-directory: ../..
        run: npm audit --audit-level=high

      - name: Audit backend
        working-directory: ../../backend
        run: npm audit --audit-level=high

      - name: Audit frontend
        working-directory: ../../frontend
        run: npm audit --audit-level=high

      # LINT
      - name: Check code
        working-directory: ../..
        run: npm run lint --workspace backend
        run: npm run lint --workspace frontend

      # RUN TESTS
      - name: Run tests on
        working-directory: ../..
        run: npm test --workspace backend
        run: npm test --workspace frontend
